[book]
title = "Creatividad Visual para no-creativos: Estrategias para tu día a día"
authors = ["Carlo Gilmar"]
description = "Visual Thinking Series"
language = "es"

[output.html]
additional-css = ["custom.css"]

[output.pdf]
display-header-footer = true
header-template = "<p style='font-size:12px; margin-left: 45%; color: #bcbcbc;'>Creatividad Visual</p>"
footer-template = "<p style='font-size:10px; margin-left: 48%; color: #bcbcbc;'><span class='pageNumber'></span> / <span class='totalPages'></span></p>"
prefer-css-page-size = true
generate-document-outline = false
margin-top = 1
margin-bottom = 1
margin-left = 0.5
margin-right = 0.5
paper-width = 7
paper-height = 9
additional-css = ["custom.css"]

[output.html.print]
enable = true